import React, { useState, useEffect } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { 
  ArrowLeft, Eye, Users, BarChart2, TrendingUp, Copy, Check,
  ExternalLink, Edit, Download, Calendar, Globe, Smartphone,
  Laptop, MoreHorizontal
} from 'lucide-react';
import { api } from '@/lib/api';

// KPI Card Component
const KPICard = ({ icon: Icon, label, value, subValue, trend, color = 'teal' }) => {
  const colorClasses = {
    teal: 'bg-teal-500/10 text-teal-400',
    green: 'bg-green-500/10 text-green-400',
    yellow: 'bg-yellow-500/10 text-yellow-400',
    gray: 'bg-gray-500/10 text-gray-400'
  };
  
  return (
    <div className="bg-gray-900 border border-gray-800 rounded-xl p-6">
      <div className="flex items-start justify-between mb-4">
        <div className={`p-3 rounded-lg ${colorClasses[color]}`}>
          <Icon size={24} />
        </div>
        {trend && (
          <span className={`text-sm font-medium ${trend > 0 ? 'text-green-400' : 'text-red-400'}`}>
            {trend > 0 ? '+' : ''}{trend}%
          </span>
        )}
      </div>
      <p className="text-3xl font-bold text-white mb-1">{value}</p>
      <p className="text-gray-400 text-sm">{label}</p>
      {subValue && <p className="text-gray-500 text-xs mt-1">{subValue}</p>}
    </div>
  );
};

// Simple Chart Component (Bar Chart)
const SimpleBarChart = ({ data, height = 200 }) => {
  const maxValue = Math.max(...data.map(d => d.value), 1);
  
  return (
    <div className="flex items-end gap-2 justify-between" style={{ height }}>
      {data.map((item, index) => (
        <div key={index} className="flex-1 flex flex-col items-center gap-2">
          <div 
            className="w-full bg-teal-500/20 rounded-t hover:bg-teal-500/30 transition-colors relative group"
            style={{ height: `${(item.value / maxValue) * 100}%`, minHeight: 4 }}
          >
            <div 
              className="absolute bottom-0 left-0 right-0 bg-teal-500 rounded-t transition-all"
              style={{ height: `${(item.leads / Math.max(item.value, 1)) * 100}%` }}
            />
            {/* Tooltip */}
            <div className="absolute -top-12 left-1/2 -translate-x-1/2 bg-gray-800 text-white text-xs px-2 py-1 rounded opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap z-10">
              {item.value} Views / {item.leads} Leads
            </div>
          </div>
          <span className="text-gray-500 text-xs">{item.label}</span>
        </div>
      ))}
    </div>
  );
};

// Lead Row Component
const LeadRow = ({ lead }) => (
  <tr className="hover:bg-gray-800/50 transition-colors">
    <td className="px-6 py-4">
      <div className="flex items-center gap-3">
        <div className="w-8 h-8 rounded-full bg-gray-700 flex items-center justify-center text-white text-sm font-medium">
          {lead.first_name?.[0]}{lead.last_name?.[0] || ''}
        </div>
        <span className="font-medium text-white">
          {lead.first_name} {lead.last_name || ''}
        </span>
      </div>
    </td>
    <td className="px-6 py-4 text-gray-400">{lead.email}</td>
    <td className="px-6 py-4 text-gray-400">
      {lead.phone || '-'}
    </td>
    <td className="px-6 py-4 text-gray-500 text-sm">
      {new Date(lead.created_at).toLocaleDateString('de-DE', {
        day: '2-digit',
        month: '2-digit',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      })}
    </td>
    <td className="px-6 py-4 text-right">
      <Link 
        to={`/leads/${lead.id}`}
        className="text-teal-400 hover:text-teal-300 font-medium text-sm"
      >
        Profil öffnen →
      </Link>
    </td>
  </tr>
);

// Main Page Component
const FreebieStatsPage = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  
  const [freebie, setFreebie] = useState(null);
  const [leads, setLeads] = useState([]);
  const [chartData, setChartData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);
  const [timeRange, setTimeRange] = useState('30'); // days

  useEffect(() => {
    loadData();
  }, [id, timeRange]);

  const loadData = async () => {
    try {
      setLoading(true);
      
      // Load freebie details
      const freebieData = await api.get(`/freebies/${id}`);
      setFreebie(freebieData);
      
      // Load leads generated by this freebie
      try {
        const leadsData = await api.get(`/freebies/${id}/leads`);
        setLeads(Array.isArray(leadsData) ? leadsData : []);
      } catch (err) {
        console.warn('Could not load leads:', err);
        setLeads([]);
      }
      
      // Load chart data
      try {
        const statsData = await api.get(`/freebies/${id}/stats?days=${timeRange}`);
        setChartData(statsData?.daily || generateMockChartData());
      } catch (err) {
        console.warn('Could not load stats:', err);
        setChartData(generateMockChartData());
      }
      
    } catch (error) {
      console.error('Error loading freebie stats:', error);
    } finally {
      setLoading(false);
    }
  };

  // Generate mock chart data for demo
  const generateMockChartData = () => {
    const days = parseInt(timeRange);
    const labels = days <= 7 
      ? ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'].slice(0, days)
      : Array.from({ length: Math.min(days, 12) }, (_, i) => `${i + 1}`);
    
    return labels.map(label => ({
      label,
      value: Math.floor(Math.random() * 50) + 5,
      leads: Math.floor(Math.random() * 10)
    }));
  };

  const handleCopyLink = () => {
    const url = `${window.location.origin}/f/${freebie.slug}`;
    navigator.clipboard.writeText(url);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportCSV = () => {
    if (leads.length === 0) return;
    
    const headers = ['Vorname', 'Nachname', 'Email', 'Telefon', 'Datum'];
    const rows = leads.map(l => [
      l.first_name,
      l.last_name || '',
      l.email,
      l.phone || '',
      new Date(l.created_at).toLocaleDateString('de-DE')
    ]);
    
    const csv = [headers, ...rows].map(row => row.join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `leads-${freebie.slug}-${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-950 flex items-center justify-center">
        <div className="animate-spin rounded-full h-8 w-8 border-t-2 border-b-2 border-teal-500" />
      </div>
    );
  }

  if (!freebie) {
    return (
      <div className="min-h-screen bg-gray-950 flex items-center justify-center">
        <div className="text-center">
          <h2 className="text-xl font-bold text-white mb-2">Freebie nicht gefunden</h2>
          <button onClick={() => navigate('/freebies')} className="text-teal-400 hover:text-teal-300">
            Zurück zur Übersicht
          </button>
        </div>
      </div>
    );
  }

  const conversionRate = freebie.views > 0 
    ? ((freebie.leads || leads.length) / freebie.views * 100).toFixed(1) 
    : 0;

  return (
    <div className="min-h-screen bg-gray-950 p-6">
      <div className="max-w-7xl mx-auto">
        
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
          <div className="flex items-center gap-4">
            <button
              onClick={() => navigate('/freebies')}
              className="p-2 text-gray-400 hover:text-white transition-colors"
            >
              <ArrowLeft size={24} />
            </button>
            <div>
              <div className="flex items-center gap-3">
                <h1 className="text-2xl font-bold text-white">{freebie.title}</h1>
                <span className={`px-2.5 py-0.5 rounded-full text-xs font-bold border ${
                  freebie.active 
                    ? 'bg-teal-500/10 text-teal-400 border-teal-500/20' 
                    : 'bg-gray-700/50 text-gray-400 border-gray-600'
                }`}>
                  {freebie.active ? 'Aktiv' : 'Entwurf'}
                </span>
              </div>
              <p className="text-gray-400 text-sm mt-1">
                Erstellt am {new Date(freebie.created_at || Date.now()).toLocaleDateString('de-DE')}
              </p>
            </div>
          </div>
          
          <div className="flex items-center gap-3">
            <button
              onClick={handleCopyLink}
              className="flex items-center gap-2 px-4 py-2 bg-gray-800 text-white rounded-lg border border-gray-700 hover:border-gray-600 transition-colors"
            >
              {copied ? <Check size={18} /> : <Copy size={18} />}
              {copied ? 'Kopiert!' : 'Link kopieren'}
            </button>
            
            <a
              href={`/f/${freebie.slug}`}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-2 px-4 py-2 bg-gray-800 text-white rounded-lg border border-gray-700 hover:border-gray-600 transition-colors"
            >
              <ExternalLink size={18} />
              Vorschau
            </a>
            <button
              onClick={() => navigate(`/freebies/${id}/edit`)}
              className="flex items-center gap-2 px-4 py-2 bg-teal-600 text-white rounded-lg hover:bg-teal-500 transition-colors"
            >
              <Edit size={18} />
              Bearbeiten
            </button>
          </div>
        </div>

        {/* KPI Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
          <KPICard 
            icon={Eye}
            label="Aufrufe (Views)"
            value={freebie.views || 0}
            subValue="Letzte 30 Tage"
          />
          <KPICard 
            icon={Users}
            label="Generierte Leads"
            value={freebie.leads || leads.length}
            subValue={`${leads.length} in der Datenbank`}
          />
          <KPICard 
            icon={TrendingUp}
            label="Conversion Rate"
            value={`${conversionRate}%`}
            subValue={conversionRate > 20 ? 'Überdurchschnittlich!' : 'Optimierbar'}
            color={conversionRate > 20 ? 'green' : conversionRate > 10 ? 'yellow' : 'gray'}
          />
          <KPICard 
            icon={Download}
            label="Downloads"
            value={freebie.downloads || 0}
            subValue="Erfolgreiche Zustellungen"
          />
        </div>

        {/* Chart Section */}
        <div className="bg-gray-900 border border-gray-800 rounded-xl p-6 mb-8">
          <div className="flex items-center justify-between mb-6">
            <div>
              <h2 className="text-lg font-semibold text-white">Views & Leads Verlauf</h2>
              <p className="text-gray-400 text-sm">Teal = Leads, Transparent = Views</p>
            </div>
            <select
              value={timeRange}
              onChange={(e) => setTimeRange(e.target.value)}
              className="bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm focus:border-teal-500 outline-none"
            >
              <option value="7">Letzte 7 Tage</option>
              <option value="30">Letzte 30 Tage</option>
              <option value="90">Letzte 90 Tage</option>
            </select>
          </div>
          
          <SimpleBarChart data={chartData} height={200} />
        </div>

        {/* Leads Table */}
        <div className="bg-gray-900 border border-gray-800 rounded-xl overflow-hidden">
          <div className="px-6 py-4 border-b border-gray-800 flex items-center justify-between">
            <div>
              <h2 className="font-semibold text-white">Generierte Leads</h2>
              <p className="text-gray-400 text-sm">{leads.length} Leads insgesamt</p>
            </div>
            <button 
              onClick={handleExportCSV}
              disabled={leads.length === 0}
              className="text-sm text-teal-400 hover:text-teal-300 disabled:text-gray-600 disabled:cursor-not-allowed font-medium"
            >
              Als CSV exportieren
            </button>
          </div>
          
          {leads.length > 0 ? (
            <div className="overflow-x-auto">
              <table className="w-full text-left text-sm">
                <thead className="bg-gray-950 text-gray-500 uppercase font-medium text-xs">
                  <tr>
                    <th className="px-6 py-3">Name</th>
                    <th className="px-6 py-3">Email</th>
                    <th className="px-6 py-3">Telefon</th>
                    <th className="px-6 py-3">Datum</th>
                    <th className="px-6 py-3 text-right">Aktion</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-800">
                  {leads.slice(0, 20).map((lead) => (
                    <LeadRow key={lead.id} lead={lead} />
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <div className="p-12 text-center">
              <Users size={48} className="mx-auto mb-4 text-gray-600" />
              <h3 className="text-white font-medium mb-2">Noch keine Leads</h3>
              <p className="text-gray-400 text-sm">
                Teile deinen Link um Leads zu generieren!
              </p>
            </div>
          )}
          
          {leads.length > 20 && (
            <div className="px-6 py-4 border-t border-gray-800 text-center">
              <button className="text-teal-400 hover:text-teal-300 text-sm font-medium">
                Alle {leads.length} Leads anzeigen
              </button>
            </div>
          )}
        </div>

      </div>
    </div>
  );
};

export default FreebieStatsPage;

