-- ╔════════════════════════════════════════════════════════════════════════════╗
-- ║  SALES FLOW AI - DAILY FLOW AGENT SYSTEM                                  ║
-- ║  Migration 009: Tagespläne, Ziele und Daily Actions                       ║
-- ╚════════════════════════════════════════════════════════════════════════════╝
--
-- Dieses Modul ermöglicht:
--   • User-Ziele definieren (Deals pro Monat, Umsatz)
--   • Automatische Tagesplan-Generierung basierend auf Conversion Rates
--   • Tracking von Daily Actions (new_contact, followup, reactivation)
--   • Fortschritts-Monitoring und Statistiken
--
-- ============================================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ═══════════════════════════════════════════════════════════════════════════
-- 1. DAILY FLOW CONFIG (User-Ziele & Einstellungen)
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.daily_flow_config (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Ziele
  target_period TEXT DEFAULT 'month' CHECK (target_period IN ('week', 'month', 'quarter')),
  target_deals_per_period INTEGER,
  target_revenue_per_period NUMERIC(10,2),
  
  -- Arbeitsrahmen
  working_days_per_week INTEGER DEFAULT 5 CHECK (working_days_per_week BETWEEN 1 AND 7),
  max_actions_per_day INTEGER DEFAULT 40 CHECK (max_actions_per_day BETWEEN 5 AND 100),
  new_to_followup_ratio NUMERIC(3,2) DEFAULT 0.40 CHECK (new_to_followup_ratio BETWEEN 0 AND 1),
  
  -- Conversion Rates (falls keine Analytics-Daten vorhanden)
  manual_contact_to_deal_rate NUMERIC(4,3) DEFAULT 0.05,
  
  -- Settings
  timezone TEXT DEFAULT 'Europe/Vienna',
  preferred_start_time TIME DEFAULT '09:00:00',
  is_active BOOLEAN DEFAULT true,
  
  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  
  -- Ein User hat nur eine aktive Config
  UNIQUE(user_id)
);

COMMENT ON TABLE public.daily_flow_config IS 'User configuration for Daily Flow Agent - goals, work preferences, conversion rates';
COMMENT ON COLUMN public.daily_flow_config.target_period IS 'Zeitraum für Zielsetzung: week, month, quarter';
COMMENT ON COLUMN public.daily_flow_config.target_deals_per_period IS 'Angestrebte Anzahl Abschlüsse pro Periode';
COMMENT ON COLUMN public.daily_flow_config.new_to_followup_ratio IS 'Verhältnis neue Kontakte zu Follow-ups (0.4 = 40% neue, 60% Follow-ups)';

-- ═══════════════════════════════════════════════════════════════════════════
-- 2. DAILY PLANS (Tagespläne)
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.daily_plans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  plan_date DATE NOT NULL,
  
  -- Status des Tagesplans
  state TEXT DEFAULT 'PLANNED' CHECK (state IN (
    'NOT_CONFIGURED',  -- Keine Ziele definiert
    'PLANNED',         -- Plan erstellt, noch nicht begonnen
    'IN_PROGRESS',     -- User arbeitet aktiv am Plan
    'COMPLETED',       -- >= 80% erledigt
    'BLOCKED'          -- Problem (keine Leads, etc.)
  )),
  
  -- Ziel-Zusammenfassung für den Tag
  target_deals_for_period INTEGER,
  planned_new_contacts INTEGER DEFAULT 0,
  planned_followups INTEGER DEFAULT 0,
  planned_actions_total INTEGER DEFAULT 0,
  
  -- Tages-Statistiken
  actions_done INTEGER DEFAULT 0,
  actions_skipped INTEGER DEFAULT 0,
  actions_snoozed INTEGER DEFAULT 0,
  
  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  
  -- Ein Plan pro User pro Tag
  UNIQUE(user_id, plan_date)
);

COMMENT ON TABLE public.daily_plans IS 'Daily plans generated by Daily Flow Agent';
COMMENT ON COLUMN public.daily_plans.state IS 'Status: NOT_CONFIGURED, PLANNED, IN_PROGRESS, COMPLETED, BLOCKED';

-- Index für schnelle Abfragen
CREATE INDEX IF NOT EXISTS idx_daily_plans_user_date 
  ON public.daily_plans(user_id, plan_date DESC);

CREATE INDEX IF NOT EXISTS idx_daily_plans_state 
  ON public.daily_plans(state);

-- ═══════════════════════════════════════════════════════════════════════════
-- 3. DAILY ACTIONS (Einzelaktionen pro Tag)
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.daily_actions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  daily_plan_id UUID NOT NULL REFERENCES public.daily_plans(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Verknüpfung zu anderen Entitäten
  lead_id UUID REFERENCES public.leads(id) ON DELETE SET NULL,
  followup_id UUID REFERENCES public.follow_up_tasks(id) ON DELETE SET NULL,
  
  -- Action Details
  action_type TEXT NOT NULL CHECK (action_type IN (
    'new_contact',      -- Neuen Lead kontaktieren
    'followup',         -- Follow-up durchführen
    'reactivation',     -- Inaktiven Lead reaktivieren
    'pipeline_cleanup', -- Pipeline aufräumen
    'admin'             -- Administrative Aufgabe
  )),
  
  channel TEXT DEFAULT 'whatsapp' CHECK (channel IN (
    'whatsapp', 'email', 'phone', 'social', 'in_person', 'other'
  )),
  
  title TEXT NOT NULL,
  description TEXT,
  
  -- Status
  status TEXT DEFAULT 'pending' CHECK (status IN (
    'pending',     -- Noch nicht bearbeitet
    'in_progress', -- Gerade in Bearbeitung
    'done',        -- Erfolgreich erledigt
    'skipped',     -- Übersprungen
    'snoozed'      -- Auf später verschoben
  )),
  
  -- Zeitplanung
  due_at TIMESTAMPTZ NOT NULL,
  priority INTEGER DEFAULT 0,  -- Höher = wichtiger
  
  -- Quelle der Action
  source TEXT DEFAULT 'goal_engine' CHECK (source IN (
    'goal_engine',        -- Automatisch aus Ziel-Berechnung
    'followup_system',    -- Aus Follow-up System
    'next_best_actions',  -- Aus NBA System
    'manual'              -- Manuell hinzugefügt
  )),
  
  -- Snooze-Daten
  snoozed_until TIMESTAMPTZ,
  
  -- Ergebnis
  completed_at TIMESTAMPTZ,
  skip_reason TEXT,
  notes TEXT,
  
  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

COMMENT ON TABLE public.daily_actions IS 'Individual actions within a daily plan';
COMMENT ON COLUMN public.daily_actions.action_type IS 'Art der Aktion: new_contact, followup, reactivation, pipeline_cleanup, admin';
COMMENT ON COLUMN public.daily_actions.source IS 'Woher die Aktion stammt: goal_engine, followup_system, next_best_actions, manual';

-- Indexes für Performance
CREATE INDEX IF NOT EXISTS idx_daily_actions_plan 
  ON public.daily_actions(daily_plan_id);

CREATE INDEX IF NOT EXISTS idx_daily_actions_user 
  ON public.daily_actions(user_id);

CREATE INDEX IF NOT EXISTS idx_daily_actions_status 
  ON public.daily_actions(status);

CREATE INDEX IF NOT EXISTS idx_daily_actions_due 
  ON public.daily_actions(due_at);

CREATE INDEX IF NOT EXISTS idx_daily_actions_lead 
  ON public.daily_actions(lead_id) WHERE lead_id IS NOT NULL;

-- ═══════════════════════════════════════════════════════════════════════════
-- 4. TRIGGER: Auto-Update updated_at
-- ═══════════════════════════════════════════════════════════════════════════

-- Config updated_at
CREATE OR REPLACE FUNCTION update_daily_flow_config_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_daily_flow_config_updated_at ON public.daily_flow_config;
CREATE TRIGGER trigger_daily_flow_config_updated_at
  BEFORE UPDATE ON public.daily_flow_config
  FOR EACH ROW
  EXECUTE FUNCTION update_daily_flow_config_updated_at();

-- Plans updated_at
CREATE OR REPLACE FUNCTION update_daily_plans_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_daily_plans_updated_at ON public.daily_plans;
CREATE TRIGGER trigger_daily_plans_updated_at
  BEFORE UPDATE ON public.daily_plans
  FOR EACH ROW
  EXECUTE FUNCTION update_daily_plans_updated_at();

-- Actions updated_at
CREATE OR REPLACE FUNCTION update_daily_actions_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_daily_actions_updated_at ON public.daily_actions;
CREATE TRIGGER trigger_daily_actions_updated_at
  BEFORE UPDATE ON public.daily_actions
  FOR EACH ROW
  EXECUTE FUNCTION update_daily_actions_updated_at();

-- ═══════════════════════════════════════════════════════════════════════════
-- 5. RPC: Get or Create Today's Plan
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.get_or_create_daily_plan(
  p_user_id UUID,
  p_date DATE DEFAULT CURRENT_DATE
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_plan_id UUID;
  v_config daily_flow_config%ROWTYPE;
BEGIN
  -- Prüfen ob Plan bereits existiert
  SELECT id INTO v_plan_id
  FROM daily_plans
  WHERE user_id = p_user_id AND plan_date = p_date;
  
  IF v_plan_id IS NOT NULL THEN
    RETURN v_plan_id;
  END IF;
  
  -- Config laden
  SELECT * INTO v_config
  FROM daily_flow_config
  WHERE user_id = p_user_id AND is_active = true;
  
  IF v_config IS NULL THEN
    -- Leeren Plan mit NOT_CONFIGURED Status erstellen
    INSERT INTO daily_plans (user_id, plan_date, state)
    VALUES (p_user_id, p_date, 'NOT_CONFIGURED')
    RETURNING id INTO v_plan_id;
  ELSE
    -- Plan mit PLANNED Status erstellen (Actions werden separat generiert)
    INSERT INTO daily_plans (
      user_id, plan_date, state,
      target_deals_for_period
    )
    VALUES (
      p_user_id, p_date, 'PLANNED',
      v_config.target_deals_per_period
    )
    RETURNING id INTO v_plan_id;
  END IF;
  
  RETURN v_plan_id;
END;
$$;

COMMENT ON FUNCTION public.get_or_create_daily_plan IS 'Holt oder erstellt einen Tagesplan für einen User';

-- ═══════════════════════════════════════════════════════════════════════════
-- 6. RPC: Update Action Status
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.update_daily_action_status(
  p_action_id UUID,
  p_status TEXT,
  p_notes TEXT DEFAULT NULL,
  p_skip_reason TEXT DEFAULT NULL,
  p_snoozed_until TIMESTAMPTZ DEFAULT NULL
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_plan_id UUID;
  v_old_status TEXT;
  v_total_actions INTEGER;
  v_done_actions INTEGER;
BEGIN
  -- Aktuellen Status und Plan-ID holen
  SELECT daily_plan_id, status INTO v_plan_id, v_old_status
  FROM daily_actions
  WHERE id = p_action_id;
  
  IF v_plan_id IS NULL THEN
    RETURN FALSE;
  END IF;
  
  -- Action aktualisieren
  UPDATE daily_actions
  SET 
    status = p_status,
    notes = COALESCE(p_notes, notes),
    skip_reason = CASE WHEN p_status = 'skipped' THEN p_skip_reason ELSE skip_reason END,
    snoozed_until = CASE WHEN p_status = 'snoozed' THEN p_snoozed_until ELSE snoozed_until END,
    completed_at = CASE WHEN p_status = 'done' THEN NOW() ELSE completed_at END,
    updated_at = NOW()
  WHERE id = p_action_id;
  
  -- Plan-Statistiken aktualisieren
  IF p_status = 'done' AND v_old_status != 'done' THEN
    UPDATE daily_plans 
    SET actions_done = actions_done + 1, 
        state = CASE WHEN state = 'PLANNED' THEN 'IN_PROGRESS' ELSE state END,
        updated_at = NOW() 
    WHERE id = v_plan_id;
  ELSIF p_status = 'skipped' AND v_old_status != 'skipped' THEN
    UPDATE daily_plans 
    SET actions_skipped = actions_skipped + 1, 
        updated_at = NOW() 
    WHERE id = v_plan_id;
  ELSIF p_status = 'snoozed' AND v_old_status != 'snoozed' THEN
    UPDATE daily_plans 
    SET actions_snoozed = actions_snoozed + 1, 
        updated_at = NOW() 
    WHERE id = v_plan_id;
  END IF;
  
  -- Prüfen ob Plan als COMPLETED markiert werden soll (>= 80% erledigt)
  SELECT planned_actions_total, actions_done 
  INTO v_total_actions, v_done_actions
  FROM daily_plans 
  WHERE id = v_plan_id;
  
  IF v_total_actions > 0 AND (v_done_actions::FLOAT / v_total_actions::FLOAT) >= 0.8 THEN
    UPDATE daily_plans
    SET state = 'COMPLETED', updated_at = NOW()
    WHERE id = v_plan_id AND state != 'COMPLETED';
  END IF;
  
  RETURN TRUE;
END;
$$;

COMMENT ON FUNCTION public.update_daily_action_status IS 'Aktualisiert den Status einer Daily Action und updated Plan-Statistiken';

-- ═══════════════════════════════════════════════════════════════════════════
-- 7. RPC: Get Conversion Rates from Analytics
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.get_conversion_rates(
  p_user_id UUID,
  p_days_back INTEGER DEFAULT 90
)
RETURNS TABLE (
  contact_to_conversation NUMERIC,
  conversation_to_deal NUMERIC,
  overall_contact_to_deal NUMERIC,
  total_contacts BIGINT,
  total_contacted BIGINT,
  total_converted BIGINT
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_total_contacts BIGINT;
  v_contacted BIGINT;
  v_converted BIGINT;
BEGIN
  -- Statistiken aus Leads-Tabelle berechnen
  SELECT 
    COUNT(*),
    COUNT(*) FILTER (WHERE last_contact_at IS NOT NULL OR status NOT IN ('new', 'cold')),
    COUNT(*) FILTER (WHERE status IN ('converted', 'won', 'customer'))
  INTO v_total_contacts, v_contacted, v_converted
  FROM leads
  WHERE user_id = p_user_id
    AND created_at >= NOW() - (p_days_back || ' days')::INTERVAL;
  
  RETURN QUERY SELECT
    -- Kontakt zu Gespräch Rate
    CASE WHEN v_total_contacts > 0 
      THEN ROUND((v_contacted::NUMERIC / v_total_contacts::NUMERIC), 3) 
      ELSE 0.40 END AS contact_to_conversation,
    -- Gespräch zu Deal Rate
    CASE WHEN v_contacted > 0 
      THEN ROUND((v_converted::NUMERIC / v_contacted::NUMERIC), 3) 
      ELSE 0.20 END AS conversation_to_deal,
    -- Gesamte Kontakt zu Deal Rate
    CASE WHEN v_total_contacts > 0 
      THEN ROUND((v_converted::NUMERIC / v_total_contacts::NUMERIC), 3) 
      ELSE 0.05 END AS overall_contact_to_deal,
    v_total_contacts AS total_contacts,
    v_contacted AS total_contacted,
    v_converted AS total_converted;
END;
$$;

COMMENT ON FUNCTION public.get_conversion_rates IS 'Berechnet Conversion Rates aus historischen Lead-Daten';

-- ═══════════════════════════════════════════════════════════════════════════
-- 8. RPC: Get Daily Statistics
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.get_daily_stats(
  p_user_id UUID,
  p_date DATE DEFAULT CURRENT_DATE
)
RETURNS TABLE (
  plan_id UUID,
  plan_state TEXT,
  planned_total INTEGER,
  actions_done INTEGER,
  actions_skipped INTEGER,
  actions_snoozed INTEGER,
  progress_percent INTEGER,
  pending_count BIGINT,
  new_contacts_done BIGINT,
  followups_done BIGINT
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    dp.id AS plan_id,
    dp.state AS plan_state,
    dp.planned_actions_total AS planned_total,
    dp.actions_done,
    dp.actions_skipped,
    dp.actions_snoozed,
    CASE 
      WHEN dp.planned_actions_total > 0 
      THEN ROUND((dp.actions_done::FLOAT / dp.planned_actions_total::FLOAT) * 100)::INTEGER
      ELSE 0 
    END AS progress_percent,
    (SELECT COUNT(*) FROM daily_actions da WHERE da.daily_plan_id = dp.id AND da.status = 'pending') AS pending_count,
    (SELECT COUNT(*) FROM daily_actions da WHERE da.daily_plan_id = dp.id AND da.action_type = 'new_contact' AND da.status = 'done') AS new_contacts_done,
    (SELECT COUNT(*) FROM daily_actions da WHERE da.daily_plan_id = dp.id AND da.action_type = 'followup' AND da.status = 'done') AS followups_done
  FROM daily_plans dp
  WHERE dp.user_id = p_user_id AND dp.plan_date = p_date;
END;
$$;

COMMENT ON FUNCTION public.get_daily_stats IS 'Holt Tagesstatistiken für einen User';

-- ═══════════════════════════════════════════════════════════════════════════
-- 9. VIEW: Actions mit Lead-Daten
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE VIEW public.v_daily_actions_with_leads AS
SELECT 
  da.*,
  l.name AS lead_name,
  l.email AS lead_email,
  l.phone AS lead_phone,
  l.status AS lead_status,
  l.source AS lead_source,
  ft.description AS followup_description,
  ft.priority AS followup_priority
FROM public.daily_actions da
LEFT JOIN public.leads l ON da.lead_id = l.id
LEFT JOIN public.follow_up_tasks ft ON da.followup_id = ft.id
ORDER BY da.priority DESC, da.due_at ASC;

COMMENT ON VIEW public.v_daily_actions_with_leads IS 'Daily Actions mit verknüpften Lead- und Follow-up-Daten';

-- ═══════════════════════════════════════════════════════════════════════════
-- 10. RLS POLICIES
-- ═══════════════════════════════════════════════════════════════════════════

-- Config RLS
ALTER TABLE public.daily_flow_config ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "daily_flow_config_select_own" ON public.daily_flow_config;
CREATE POLICY "daily_flow_config_select_own"
ON public.daily_flow_config FOR SELECT
USING (user_id = auth.uid());

DROP POLICY IF EXISTS "daily_flow_config_insert_own" ON public.daily_flow_config;
CREATE POLICY "daily_flow_config_insert_own"
ON public.daily_flow_config FOR INSERT
WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "daily_flow_config_update_own" ON public.daily_flow_config;
CREATE POLICY "daily_flow_config_update_own"
ON public.daily_flow_config FOR UPDATE
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "daily_flow_config_delete_own" ON public.daily_flow_config;
CREATE POLICY "daily_flow_config_delete_own"
ON public.daily_flow_config FOR DELETE
USING (user_id = auth.uid());

-- Plans RLS
ALTER TABLE public.daily_plans ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "daily_plans_select_own" ON public.daily_plans;
CREATE POLICY "daily_plans_select_own"
ON public.daily_plans FOR SELECT
USING (user_id = auth.uid());

DROP POLICY IF EXISTS "daily_plans_insert_own" ON public.daily_plans;
CREATE POLICY "daily_plans_insert_own"
ON public.daily_plans FOR INSERT
WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "daily_plans_update_own" ON public.daily_plans;
CREATE POLICY "daily_plans_update_own"
ON public.daily_plans FOR UPDATE
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "daily_plans_delete_own" ON public.daily_plans;
CREATE POLICY "daily_plans_delete_own"
ON public.daily_plans FOR DELETE
USING (user_id = auth.uid());

-- Actions RLS
ALTER TABLE public.daily_actions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "daily_actions_select_own" ON public.daily_actions;
CREATE POLICY "daily_actions_select_own"
ON public.daily_actions FOR SELECT
USING (user_id = auth.uid());

DROP POLICY IF EXISTS "daily_actions_insert_own" ON public.daily_actions;
CREATE POLICY "daily_actions_insert_own"
ON public.daily_actions FOR INSERT
WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "daily_actions_update_own" ON public.daily_actions;
CREATE POLICY "daily_actions_update_own"
ON public.daily_actions FOR UPDATE
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "daily_actions_delete_own" ON public.daily_actions;
CREATE POLICY "daily_actions_delete_own"
ON public.daily_actions FOR DELETE
USING (user_id = auth.uid());

-- ═══════════════════════════════════════════════════════════════════════════
-- 11. GRANTS
-- ═══════════════════════════════════════════════════════════════════════════

GRANT ALL ON public.daily_flow_config TO authenticated;
GRANT ALL ON public.daily_plans TO authenticated;
GRANT ALL ON public.daily_actions TO authenticated;
GRANT SELECT ON public.v_daily_actions_with_leads TO authenticated;

GRANT EXECUTE ON FUNCTION public.get_or_create_daily_plan TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_daily_action_status TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_conversion_rates TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_daily_stats TO authenticated;

-- ═══════════════════════════════════════════════════════════════════════════
-- SUCCESS MESSAGE
-- ═══════════════════════════════════════════════════════════════════════════

DO $$
BEGIN
  RAISE NOTICE '';
  RAISE NOTICE '╔══════════════════════════════════════════════════════════════╗';
  RAISE NOTICE '║  ✅ DAILY FLOW AGENT SYSTEM INSTALLED SUCCESSFULLY!         ║';
  RAISE NOTICE '╚══════════════════════════════════════════════════════════════╝';
  RAISE NOTICE '';
  RAISE NOTICE '📋 Created Tables:';
  RAISE NOTICE '   • daily_flow_config (User-Ziele & Einstellungen)';
  RAISE NOTICE '   • daily_plans (Tagespläne)';
  RAISE NOTICE '   • daily_actions (Einzelaktionen)';
  RAISE NOTICE '';
  RAISE NOTICE '🔧 Created Functions:';
  RAISE NOTICE '   • get_or_create_daily_plan() - Tagesplan holen/erstellen';
  RAISE NOTICE '   • update_daily_action_status() - Action-Status ändern';
  RAISE NOTICE '   • get_conversion_rates() - Conversion Rates berechnen';
  RAISE NOTICE '   • get_daily_stats() - Tagesstatistiken abrufen';
  RAISE NOTICE '';
  RAISE NOTICE '👁️ Created Views:';
  RAISE NOTICE '   • v_daily_actions_with_leads - Actions mit Lead-Daten';
  RAISE NOTICE '';
  RAISE NOTICE '🔒 RLS enabled - users can only access their own data';
  RAISE NOTICE '';
END $$;

